#!/usr/bin/env python3
"""CLI entry point for GGML regression audit.

Usage:
    python tools/regression/audit.py <baseline_commit> [--head HEAD] [--files FILE...] [--runtime]
"""

import argparse
import html
import subprocess
import json
import os
import sys

# Add project root to path so `from tools.regression.*` imports work
_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
_PROJECT_ROOT = os.path.dirname(os.path.dirname(_SCRIPT_DIR))  # tools/regression/../.. = project root
if _PROJECT_ROOT not in sys.path:
    sys.path.insert(0, _PROJECT_ROOT)
from pathlib import Path

REPORT_DIR = Path(__file__).parent / "report"


def render_html(report: dict) -> str:
    """Build a flat HTML report from structured findings dict."""
    lines = ["<!DOCTYPE html><html><head><meta charset='utf-8'><title>GGML Regression Audit</title>",
             "<style>body{font-family:monospace;max-width:960px;margin:auto;padding:2em}"
             ".critical{color:#c00;font-weight:bold}.warning{color:#c60}table{border-collapse:collapse;width:100%}"
             "td,th{border:1px solid #ccc;padding:4px 8px;text-align:left}"
             "th{background:#eee}</style></head><body>",
             f"<h1>GGML Regression Audit</h1>",
             f"<p>Baseline: {report.get('baseline', '?')} | Head: {report.get('head', '?')}</p>"]

    if report.get("critical"):
        lines += ["<h2 class='critical'>Critical Issues</h2><ul>"]
        for item in report["critical"]:
            lines.append(f"<li>{html.escape(str(item))}</li>")
        lines.append("</ul>")

    passes = report.get("passes", {})
    for name, data in passes.items():
        lines.append(f"<h2>Pass: {html.escape(name)}</h2>")
        if data is None:
            lines.append("<p>skipped</p>")
        elif isinstance(data, str):
            lines.append(f"<pre>{html.escape(data)}</pre>")
        elif isinstance(data, list):
            if not data:
                lines.append("<p>No issues found.</p>")
            else:
                lines += ["<table><tr><th>Flag</th><th>Baseline</th><th>Head</th><th>Severity</th></tr>"]
                for row in data:
                    sev = row.get("severity", "info")
                    cls = f" class='{sev}'" if sev in ("critical", "warning") else ""
                    lines.append(f"<tr{cls}><td>{html.escape(str(row.get('flag','')))}</td>"
                                 f"<td>{html.escape(str(row.get('baseline','')))}</td>"
                                 f"<td>{html.escape(str(row.get('head','')))}</td>"
                                 f"<td>{sev}</td></tr>")
                lines.append("</table>")
        else:
            lines.append(f"<pre>{html.escape(str(data))}</pre>")

    lines.append(f"<hr><p>Generated by ggml regression audit</p></body></html>")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="GGML regression audit against a known-good baseline")
    parser.add_argument("baseline", help="Baseline commit hash (known-good)")
    parser.add_argument("--head", default="HEAD", help="Head revision to compare (default: HEAD)")
    parser.add_argument("--files", nargs="*", help="Limit audit to specific files (default: all hot-path files)")
    parser.add_argument("--runtime", action="store_true", help="Run runtime microbenchmarks (requires builds)")
    parser.add_argument("--build-dir-baseline", default=None, help="Path to baseline build dir (for config.h)")
    parser.add_argument("--build-dir-head", default=None, help="Path to HEAD build dir (for config.h)")
    args = parser.parse_args()

    report = {"baseline": args.baseline, "head": args.head, "warnings": [], "critical": [], "passes": {}}

    print(f"Baseline: {args.baseline}  Head: {args.head}")

    from tools.regression.pass_flags import run_flags_pass
    report["passes"]["flags"] = run_flags_pass(args.baseline, args.head,
                                                args.build_dir_baseline, args.build_dir_head,
                                                report["critical"], report["warnings"])

    from tools.regression.pass_compiler import run_compiler_pass
    report["passes"]["compiler"] = run_compiler_pass(args.build_dir_baseline, args.build_dir_head,
                                                      report["critical"], report["warnings"])

    from tools.regression.pass_code import run_code_pass
    report["passes"]["code"] = run_code_pass(args.baseline, args.head, args.files,
                                              report["critical"], report["warnings"])

    if args.runtime:
        from tools.regression.pass_runtime import run_runtime_pass
        report["passes"]["runtime"] = run_runtime_pass(args.baseline, args.head,
                                                        report["critical"], report["warnings"])
    else:
        report["passes"]["runtime"] = None

    html_out = render_html(report)
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    (REPORT_DIR / "report.html").write_text(html_out, encoding="utf-8")
    print(f"\nReport: {REPORT_DIR / 'report.html'}")

    if report["critical"]:
        print(f"\nCRITICAL: {len(report['critical'])} issues")
    if report["warnings"]:
        print(f"\nWARNINGS: {len(report['warnings'])} issues")
    return 0 if not report["critical"] else 1


if __name__ == "__main__":
    sys.exit(main())
